spring:
  application:
    name: maispratiforum

  datasource:
    url: jdbc:${HOST}:${PORT}/${DATA_BASE}
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
